title: Masha S
logo: /assets/img/logo1.png
description:  >  
  My name is Masha, I am a Data/Information Arhitect. I have graduated with a Master's degree in Computational Science from TU Munich in 2021. I am passionate about solution architecture and information management (data governance, data management, data architecture) for advanced data & analytics applications.
  <br><br>
  In my free time I read a lot of books which leads to me having a lot of opinions. I am interested in game and chaos theories, ancient civilizations, greek mythology, weird arthouse movies and other random (and not very random) things. 
  <br><br>
  <a href="https://www.linkedin.com/in/maria-stroganova/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

