title: Masha S
logo: /assets/img/logo1.png
description:  >  
  A place for various things. 
  <br><br>
  <a href="https://www.linkedin.com/in/maria-stroganova/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

